<?php
namespace Poplar\Core;

/**
* 系统常量
* @author yangxiaogang 2018-09-28
*/

class SysConst
{
	const VERSION = 'VERSION';

    const LOGGER_WRITER = 'LOGGER_WRITER';

    const ERROR_HANDLER = 'ERROR_HANDLER';
    const SHUTDOWN_FUNCTION = 'SHUTDOWN_FUNCTION';
    const TRIGGER_HANDLER = 'TRIGGER_HANDLER';

    const HTTP_CONTROLLER_MAX_DEPTH = 'CONTROLLER_MAX_DEPTH';
    const HTTP_EXCEPTION_HANDLER = 'HTTP_EXCEPTION_HANDLER';
    const HTTP_SESSION_HANDLER = 'HTTP_SESSION_HANDLER';
    const HTTP_SESSION_SAVE_PATH = 'HTTP_SESSION_SAVE_PATH';
    const HTTP_SESSION_NAME = 'HTTP_SESSION_NAME';
    const HTTP_SESSION_GC_PROBABILITY = 'HTTP_SESSION_GC_PROBABILITY';
    const HTTP_SESSION_GC_MAX_LIFE_TIME = 'HTTP_SESSION_GC_MAX_LIFE_TIME';
}